"""
utils/export.py

Export helpers for the recommendation results:
    export_to_excel(df, path)             -> .xlsx via pandas/openpyxl
    export_to_pdf(df, requirements, path) -> a simple summary report via fpdf2

Both take an in-memory path (BytesIO works for Streamlit's download
buttons) or a plain file path string.
"""

from __future__ import annotations

from typing import Union, IO
import pandas as pd
from fpdf import FPDF


def export_to_excel(df: pd.DataFrame, path: Union[str, IO]) -> None:
    """Write a DataFrame to an .xlsx file. Drops list-typed columns
    (Applications, Advantages, etc.) into comma-joined strings first —
    openpyxl can't write native Python lists into a cell."""
    export_df = df.copy()
    for col in export_df.columns:
        if export_df[col].apply(lambda v: isinstance(v, list)).any():
            export_df[col] = export_df[col].apply(
                lambda v: ", ".join(v) if isinstance(v, list) else v
            )
    export_df.to_excel(path, index=False, engine="openpyxl", sheet_name="Recommendations")


def export_to_pdf(df: pd.DataFrame, requirements: dict, path: Union[str, IO]) -> None:
    """Build a short, readable PDF summary: the requirements the user
    entered, followed by a table of the top recommended materials."""
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "Material Recommendation Report", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 6, "Generated by Smart Material Recommendation System", ln=True)
    pdf.ln(4)

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Requirements", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for key, value in requirements.items():
        if value is None or value == "":
            continue
        pdf.cell(0, 6, f"  - {key}: {value}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Top Recommended Materials", ln=True)
    pdf.set_font("Helvetica", "B", 9)

    columns = ["Name", "Family", "Score", "Yield Strength (MPa)", "Density (g/cm3)", "Relative Cost"]
    col_widths = [45, 30, 18, 32, 28, 25]

    for col, width in zip(columns, col_widths):
        pdf.cell(width, 7, col, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for _, row in df.head(5).iterrows():
        pdf.cell(col_widths[0], 7, str(row["Name"])[:28], border=1)
        pdf.cell(col_widths[1], 7, str(row["Family"]), border=1)
        pdf.cell(col_widths[2], 7, f"{row.get('Score', 0):.1f}", border=1)
        pdf.cell(col_widths[3], 7, str(row["Yield Strength (MPa)"]), border=1)
        pdf.cell(col_widths[4], 7, str(row["Density (g/cm3)"]), border=1)
        pdf.cell(col_widths[5], 7, str(row["Relative Cost"]), border=1)
        pdf.ln()

    pdf.output(path)
